namespace PaymentService.Data.Entities;

/// <summary>
/// EF Core entity that maps to the [Payments] table in SQL Server.
///
/// WHY a separate class from Models/Payment.cs?
///   Payment.cs carries MongoDB [Bson*] attributes and uses <c>double</c>
///   for Amount (matching the existing MongoDB schema). EF Core needs its own
///   clean POCO so the two persistence layers never collide.
///
/// WHY Guid for PK instead of int / string?
///   GUIDs can be generated client-side without a round-trip to the DB, which
///   matters once we add RabbitMQ events (Step 5) — the ID is known before the
///   INSERT completes.
///
/// WHY decimal for Amount?
///   <c>double</c> has floating-point rounding errors (0.1 + 0.2 ≠ 0.3).
///   <c>decimal</c> maps to SQL's decimal(18,2) and is exact for currency.
/// </summary>
public class PaymentEntity
{
    /// <summary>Primary key — generated by the application, not the database.</summary>
    public Guid Id { get; set; }

    /// <summary>
    /// MongoDB ObjectId of the related booking (booking-service, Node.js).
    /// Stored as a plain string because SQL Server has no ObjectId type and
    /// we do not want a foreign-key relationship across different databases.
    /// </summary>
    public string BookingId { get; set; } = string.Empty;

    /// <summary>
    /// MongoDB ObjectId of the paying user (user-service, Node.js).
    /// Same cross-database reasoning as BookingId.
    /// </summary>
    public string UserId { get; set; } = string.Empty;

    /// <summary>Payment amount in the booking currency. Uses decimal for financial accuracy.</summary>
    public decimal Amount { get; set; }

    /// <summary>"CreditCard" | "PayPal" | "BankTransfer" …</summary>
    public string PaymentMethod { get; set; } = string.Empty;

    /// <summary>"Pending" | "Completed" | "Failed"</summary>
    public string Status { get; set; } = "Completed";

    /// <summary>PayPal order ID — null for non-PayPal payments.</summary>
    public string? PayPalOrderId { get; set; }

    /// <summary>PayPal capture ID — confirms funds were moved from buyer to seller.</summary>
    public string? PayPalCaptureId { get; set; }

    /// <summary>UTC timestamp set once when the record is first inserted.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp updated on every change (status transitions, refunds, etc.).</summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
