// <auto-generated />
// This file is maintained by EF Core's migration tooling.
// It represents the full schema of the database at the time of the last migration.
// DO NOT edit this file manually — run `dotnet ef migrations add <Name>` instead.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Data;

#nullable disable

namespace PaymentService.Data.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Data.Entities.PaymentEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("BookingId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("PayPalCaptureId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PayPalOrderId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PaymentMethod")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasDefaultValue("Completed")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("BookingId")
                    .HasDatabaseName("IX_Payments_BookingId");

                b.HasIndex("CreatedAt")
                    .HasDatabaseName("IX_Payments_CreatedAt");

                b.HasIndex("Status")
                    .HasDatabaseName("IX_Payments_Status");

                b.HasIndex("UserId")
                    .HasDatabaseName("IX_Payments_UserId");

                b.HasIndex("Status", "CreatedAt")
                    .HasDatabaseName("IX_Payments_Status_CreatedAt");

                b.ToTable("Payments", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
